---
#
# HOW TO USE ANSIBLE FROM PACKER
#
# Althought this task does not make much sense and the vagrant.sh is also working fine 
# but this is a good example.
#

- hosts: all
  sudo: yes
  tasks:
   
  - name: Vagrant user creation and modification
    user: name=vagrant comment="Vagrant user" shell=/bin/bash append=yes groups="wheel" password="$6$iND4z4Gc$6AI5iC4SJn0UwoKWNgm30BRKjg2s0ojiYTAHUglPg03X9Pg1mbo6lGmcnvo4vll7i65phlOcXucYYj4NisqY/."
    
  - name: Add root to wheel
    user: name=root append=yes groups="wheel"
  
  - name: Disable requiretty
    lineinfile: dest=/etc/sudoers backrefs=yes regexp='(\s*Defaults\s*requiretty)' line='Defaults !requiretty'
    
  - name: Enable passwordless sudo to wheel
    lineinfile: 'dest=/etc/sudoers regexp="^(\s*%wheel.*)" line="%wheel ALL=(ALL) NOPASSWD: ALL"'
    
  - name: Create .ssh directory
    file: path=/home/vagrant/.ssh owner=vagrant group=vagrant state=directory mode=0700 
    
  - name: Installing wget
    yum: name=wget
    
  - name: Debugging proxy
    debug: var=proxy  
    
  - name: Fetching vagrant public key
    get_url: url=https://raw.githubusercontent.com/mitchellh/vagrant/master/keys/vagrant.pub dest='{{ item }}' mode=600 owner=vagrant group=vagrant
    with_items:
      - /home/vagrant/.ssh/authorized_keys

  - name: Fetching vagrant public key as id_rsa.pub
    get_url: url=https://raw.githubusercontent.com/mitchellh/vagrant/master/keys/vagrant.pub dest='{{ item }}' mode=644 owner=vagrant group=vagrant
    with_items:
      - /home/vagrant/.ssh/id_rsa.pub
    environment:
      https_proxy: '{{ https_proxy }}'
      
  - name: Fetching vagrant private key as id_rsa
    get_url: url=https://raw.githubusercontent.com/mitchellh/vagrant/master/keys/vagrant dest=/home/vagrant/.ssh/id_rsa mode=600 owner=vagrant group=vagrant
    environment:
      https_proxy: '{{ https_proxy }}'      
    
  - name: Downloading VBoxGuestAddition.iso
    get_url: url=http://download.virtualbox.org/virtualbox/5.1.4/VBoxGuestAdditions_5.1.4.iso dest=/root/VBoxGuestAdditions_Latest.iso mode=600 owner=root group=root
    environment:
      http_proxy: '{{ http_proxy }}'
      https_proxy: '{{ https_proxy }}' 
    
