_imagename="CentOS-6.7-x86_64-minimal.iso"
osmirror["United States"]="http://mirrors.kernel.org/centos/6/isos/x86_64/${_imagename}"
osmirror["Finland"]="http://ftp.funet.fi/pub/mirrors/centos.org/6/isos/x86_64/${_imagename}"
osmirror["Germany"]="http://mirror.eu.oneandone.net/linux/distributions/centos/6/isos/x86_64/${_imagename}"
osmirror["Hungary"]="http://ftp.freepark.org/pub/linux/distributions/centos/6/isos/x86_64/${_imagename}"
md5sum="9381a24b8bee2fed0c26896141a64b69"
